import Logo from "@/components/Logo";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <div className="flex justify-between p-5  items-center">
            <Logo />
            <Navbar />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
