import Logo from "@/components/Logo";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <div className="flex flex-col md:flex-row justify-between p-5 items-center">
          <div className="md:absolute absolute top-0 left-0 md:p-5">
            <Logo />
          </div>
          <div className="md:ml-auto md:absolute md:-top-8 right-0 md:mr-3 md:p-5">
            <Navbar />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
